name: flutter_meteor
description: Connect flutter apps to meteor data
version: 0.0.1
author: sean_hayes
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies: 
  uuid: ^3.0.4
  web_socket_channel: ^2.1.0
